#!/usr/bin/with-contenv bash

# Some of these docs have been pulled from Ubuntu docs:
# https://help.ubuntu.com/lts/serverguide/postfix.html
# 
# SMTP Authentication
# SMTP-AUTH allows a client to identify itself through
# an authentication mechanism (SASL). TLS should be used
# to encrypt the authentication process. Once authenticated
# the SMTP server will allow the client to relay mail.
#

postconf -e 'smtpd_banner = $myhostname ESMTP $mail_name (tkf-docker-postfix)'
postconf -e 'biff = no'

# Appending the .domain is the job of the MUA let's be a di^H^Hjerk
# and not make it easy for them
postconf -e 'append_dot_mydomain = no'

# Configure the general settings
postconf -e 'myhostname = ${MAILDOMAIN}'
postconf -e 'alias_maps = hash:/config/postfix/aliases'
postconf -e 'alias_database = hash:/config/postfix/aliases'
postconf -e 'myorigin = /etc/mailname'
postconf -e 'mydestination = localhost'
postconf -e 'relayhost = ${TKF_RELAY_HOST}'
postconf -e 'mynetworks = 127.0.0.0/8'
postconf -e 'mailbox_command = procmail -a "$EXTENSION"'
postconf -e 'mailbox_size_limit = 0'
postconf -e 'recipient_delimiter = +'
postconf -e 'inet_interfaces = all'

postconf -e 'smtpd_sasl_type = dovecot'
postconf -e 'smtpd_sasl_path = private/auth'
postconf -e 'smtpd_sasl_local_domain ='
postconf -e 'smtpd_sasl_security_options = noanonymous'
postconf -e 'broken_sasl_auth_clients = yes'
postconf -e 'smtpd_sasl_auth_enable = yes'
postconf -e 'smtpd_recipient_restrictions = \
              permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination'

# Setup the TLS bits
postconf -e 'smtp_tls_security_level = may'
postconf -e 'smtpd_tls_security_level = may'
postconf -e 'smtp_tls_note_starttls_offer = yes'
postconf -e 'smtpd_tls_key_file = /config/ssl/server.key'
postconf -e 'smtpd_tls_cert_file = /config/ssl/server.crt'
postconf -e 'smtpd_tls_loglevel = 1'
postconf -e 'smtpd_tls_received_header = yes'
postconf -e 'smtpd_tls_session_cache_timeout = 3600s'
postconf -e 'tls_random_source = /dev/urandom'
postconf -e 'smtpd_tls_auth_only = no'


# If using a non-root trusted CA
postconf -e 'smtpd_tls_CAfile = /config/ssl/CAcert.crt'
