#!/usr/bin/with-contenv bash

#exec s6-setuidgid abc python /app/nginx-ldap-auth-daemon.py --host 0.0.0.0 --port 8888
#exec s6-setuidgid abc /usr/bin/smokeping --config="/etc/smokeping/config" --nodaemon

#INSTANCES=$(postmulti -l -a | awk '($3=="y") { print $1 }

exec s6-setuidgid root /usr/libexec/postfix/master -c /etc/postfix -d 2>&1
