#!/usr/bin/with-contenv bash
#
#
set -x

# Some of these docs have been pulled from Ubuntu docs:
# https://help.ubuntu.com/lts/serverguide/postfix.html
# 
# SMTP Authentication
# SMTP-AUTH allows a client to identify itself through
# an authentication mechanism (SASL). TLS should be used
# to encrypt the authentication process. Once authenticated
# the SMTP server will allow the client to relay mail.
#
# main.cf parameter doc: http://www.postfix.org/postconf.5.html
#
CONF_DIR="/config/postfix"

if [ ! -f "${CONF_DIR}/main.cf" ]; then
#  touch "${CONF_DIR}/main.cf"
#  Add better testing here
  cp -a /bootstrap/postfix/* /config/
fi

function config_pf_general()
{
  echo "Configuring general postfix params"

  postconf -c ${CONF_DIR} -e smtpd_banner=${TKF_MAILDOMAIN}\ ESMTP\ Postfix\ \(tkf-docker-postfix\)
  postconf -c ${CONF_DIR} -e biff=no
  postconf -c ${CONF_DIR} -e smtp_always_send_ehlo=yes
  postconf -c ${CONF_DIR} -e smtp_helo_name=${TKF_MAILDOMAIN}
  postconf -c ${CONF_DIR} -e append_dot_mydomain=no
  postconf -c ${CONF_DIR} -e myhostname=${TKF_MYHOSTNAME}

  # Not sure /etc/mailname is actually configured in Alpine
  postconf -c ${CONF_DIR} -e myorigin=/etc/mailname

  # mydestination is 'what domains should we accept local mail for?'
  postconf -c ${CONF_DIR} -e mydestination=localhost

  postconf -c ${CONF_DIR} -e mynetworks="${TKF_MYNETWORKS}"
  postconf -c ${CONF_DIR} -e inet_interfaces=all
}

function config_pf_aliases()
{
  echo "Configuring aliases"

  postconf -c ${CONF_DIR} -e alias_maps=hash:${CONF_DIR}/aliases
  postconf -c ${CONF_DIR} -e alias_database=hash:${CONF_DIR}/aliases

  /usr/bin/newaliases -C ${CONF_DIR}
}


function config_pf_relay()
{
  echo "Configuring external relay"

  # relayhost is the next-hop destination for non-local mail.
  # in other words, where do we send our mail out through so
  # we don't have to try to deliver it ourselves
  # Our relay host is set in the docker image via an enviornment
  # vairable that is passed in - TKF_RELAY_HOST
  postconf -c ${CONF_DIR} -e relayhost=${TKF_RELAY_HOST}

  # smtpd_relay_restrictions sets who can actually relay through
  # this host. My assumption for now is that anyone connecting from
  # 'mynetworks' is allowed. Those should be local addresses/networks
  postconf -c ${CONF_DIR} -e 'smtpd_relay_restrictions=permit_mynetworks defer_unauth_destination'
}

function config_pf_tls()
{
  echo "Configuring postfix TLS settings"

  # If the server that this postfix connects to says it does STARTTLS
  # let's try to use it. Note: I actually think we should be using
  # smtp_tls_security_level instead, not sure what happens when both
  # are configured?
  postconf -c ${CONF_DIR} -e smtp_use_tls=yes

  postconf -c ${CONF_DIR} -e smtp_tls_security_level=encrypt
  postconf -c ${CONF_DIR} -e smtpd_tls_security_level=may
  #postconf -c ${CONF_DIR} -e smtp_tls_note_starttls_offer=yes

  postconf -c ${CONF_DIR} -e smtpd_tls_key_file=/config/ssl/server.key
  postconf -c ${CONF_DIR} -e smtpd_tls_cert_file=/config/ssl/server.crt
  postconf -c ${CONF_DIR} -e smtpd_tls_CAfile=/config/ssl/CAcert.crt
  postconf -c ${CONF_DIR} -e smtpd_tls_loglevel=1
  #postconf -c ${CONF_DIR} -e 'smtpd_tls_received_header = yes'
  #postconf -c ${CONF_DIR} -e 'smtpd_tls_session_cache_timeout = 3600s'
  #postconf -c ${CONF_DIR} -e 'tls_random_source = /dev/urandom'
  #postconf -c ${CONF_DIR} -e 'smtpd_tls_auth_only = no'
}

function config_pf_sasl()
{
  echo "Configuring SASL parameters"

  # Note: I *really* dont like passing this in via env variables
  # One option is to pull this information via Vault,
  # But it is unlikely that other users have vault.
  # Might want to remove this fromt he env also after we protect it?
  echo ${TKF_RELAY_PASSWORD} > ${CONF_DIR}/relay_passwords
  postmap ${CONF_DIR}/relay_passwords
  rm -f ${CONF_DIR}/relay_passwords
  chmod 0600 ${CONF_DIR}/relay_passwords.db

  postconf -c ${CONF_DIR} -e smtp_sasl_auth_enable=yes
  postconf -c ${CONF_DIR} -e smtp_sasl_password_maps=hash:/config/postfix/relay_passwords
  postconf -c ${CONF_DIR} -e smtp_sasl_security_options=noanonymous
  postconf -c ${CONF_DIR} -e smtp_tls_note_starttls_offer=yes
}


config_pf_general
config_pf_aliases
config_pf_relay
config_pf_tls
config_pf_sasl
